FROM golang:alpine

ENV PORT=8080

WORKDIR /go/src/github.com/moorage/cloud-hugo
RUN apk -U add ca-certificates
ADD ./frontend/dist ./frontend/dist
ADD ./publisher ./publisher


EXPOSE 8080

ENTRYPOINT ["./publisher"]