kind: ConfigMap
metadata:
  creationTimestamp: null
  name: clugo-config
apiVersion: v1
data:
  pub-config.json: |-
    {
        "project_id": "cloud-hugo-test",
        "topic_name": "chugo-run-requests",
        "env": "dev",
        "pub_port": "8080",
        "user_name": "${GITHUB_USERNAME}",
        "user_email": "${GITHUB_EMAIL}",
        "access_token": "${GITHUB_ACCESS_TOKEN}",
        "repo_url": "${REPO_URL}"
    }
  sub-config.json: |-
    {
        "project_id": "cloud-hugo-test",
        "topic_name": "chugo-run-requests",
        "env": "dev",
        "sub_port": "8081",
        "user_name": "${GITHUB_USERNAME}",
        "user_email": "${GITHUB_EMAIL}",
        "access_token": "${GITHUB_ACCESS_TOKEN}",
        "repo_url": "${REPO_URL}"
    }
