apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "subscriber"
  labels: {app: "subscriber"}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "subscriber"
  template:
    metadata: {labels: {app: "subscriber"}}
    spec:
      containers:
      - name: "subscriber"
        image: "gcr.io/cloud-hugo-test/subscriber:${TAG}"
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: sub-config
            mountPath: /go/src/github.com/moorage/cloud-hugo/config/sub-config.json
            subPath: sub-config.json
          - name: clugo-secret
            mountPath: /go/src/github.com/moorage/cloud-hugo/config/credentials.json
            subPath: credentials.json     
      volumes:
        - name: sub-config
          configMap: { name: clugo-config }
        - name: clugo-secret
          configMap: { name: clugo-secret }      
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "subscriber-hpa"
  namespace: "default"
  labels:
    app: "subscriber"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "subscriber"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
kind: Service
apiVersion: v1
metadata:
  name: subscriber
spec:
  type: LoadBalancer
  selector:
    app: subscriber
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081